# Generated by Django 5.0.2 on 2024-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=60)),
                ('dt_nasc', models.CharField(max_length=60)),
                ('telefone', models.PositiveIntegerField()),
                ('cpf', models.PositiveIntegerField()),
            ],
        ),
    ]
