# Generated by Django 5.0.3 on 2024-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_alter_alunos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='sexo',
            field=models.CharField(max_length=60),
        ),
    ]
