# Generated by Django 5.0.3 on 2024-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_alter_alunos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=60),
        ),
    ]
